server:
  port: 8080
spring:
  application:
    name: lagou-service-resume
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:jdbc:mysql://localhost:3306/lucasdb?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root